name = "SimulacoesTemplate"
uuid = "90ca94d5-fe14-45ef-9d6e-d9ee7a2e7386"
authors = ["= <=> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
